/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package escalerasyserpientes;

import javax.swing.JOptionPane;

/**
 *
 * @author Equipo
 */
public class Principal extends javax.swing.JFrame {
    
    private serpientesyEscaleras juego;

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel1 = new java.awt.Panel();
        tamañotablero = new javax.swing.JComboBox<>();
        titulo = new javax.swing.JLabel();
        cantjugadores = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtNombreJ1 = new javax.swing.JTextField();
        fichaJ1 = new javax.swing.JComboBox<>();
        fichaJ2 = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        txtNombreJ2 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtNombreJ3 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtNombreJ4 = new javax.swing.JTextField();
        fichaJ4 = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        fichaJ3 = new javax.swing.JComboBox<>();
        Jugar = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panel1.setBackground(new java.awt.Color(102, 255, 102));

        tamañotablero.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "10", "13", "15" }));

        titulo.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        titulo.setText("SERPIENTES Y ESCALERAS");

        cantjugadores.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2", "3", "4" }));
        cantjugadores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cantjugadoresActionPerformed(evt);
            }
        });

        jLabel1.setText("Cantidad de Jugadores");

        jLabel2.setText("Nombre Jugador 1");

        fichaJ1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Roja", "Azul", "Verde", "Amarilla" }));
        fichaJ1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fichaJ1ActionPerformed(evt);
            }
        });

        fichaJ2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Roja", "Azul", "Verde", "Amarilla" }));

        jLabel7.setText("Ficha");

        jLabel3.setText("Nombre Jugador 2");

        txtNombreJ3.setEnabled(false);

        jLabel5.setText("Nombre Jugador 4");

        jLabel4.setText("Nombre Jugador 3");

        txtNombreJ4.setEnabled(false);

        fichaJ4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Roja", "Azul", "Verde", "Amarilla" }));
        fichaJ4.setEnabled(false);

        jLabel9.setText("Ficha");

        jLabel8.setText("Ficha");

        fichaJ3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Roja", "Azul", "Verde", "Amarilla" }));
        fichaJ3.setEnabled(false);

        Jugar.setText("Lanzar Juego");
        Jugar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JugarActionPerformed(evt);
            }
        });

        jLabel10.setText("Tamaño Tablero");

        jLabel6.setText("Ficha");

        javax.swing.GroupLayout panel1Layout = new javax.swing.GroupLayout(panel1);
        panel1.setLayout(panel1Layout);
        panel1Layout.setHorizontalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel1Layout.createSequentialGroup()
                .addGap(141, 141, 141)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addGap(27, 27, 27)
                        .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNombreJ1, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNombreJ4, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNombreJ3, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNombreJ2, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(46, 46, 46)
                        .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9))
                        .addGap(35, 35, 35)
                        .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(fichaJ3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(fichaJ1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(fichaJ4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(fichaJ2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addGap(198, 198, 198)
                        .addComponent(Jugar))
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(45, 45, 45)
                        .addComponent(cantjugadores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)
                        .addComponent(jLabel10)
                        .addGap(34, 34, 34)
                        .addComponent(tamañotablero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addGap(131, 131, 131)
                        .addComponent(titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(190, Short.MAX_VALUE))
        );
        panel1Layout.setVerticalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(titulo)
                .addGap(33, 33, 33)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tamañotablero, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(cantjugadores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel10)))
                .addGap(46, 46, 46)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(fichaJ1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNombreJ1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addGap(18, 18, 18)
                        .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jLabel7)
                            .addComponent(txtNombreJ2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(21, 21, 21)
                        .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtNombreJ3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addComponent(fichaJ2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(fichaJ3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))))
                .addGap(25, 25, 25)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(fichaJ4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNombreJ4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addGap(35, 35, 35)
                .addComponent(Jugar)
                .addContainerGap(56, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cantjugadoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cantjugadoresActionPerformed

        switch (cantjugadores.getSelectedItem().toString()){
            
            case "2" -> {
                txtNombreJ3.setEnabled(false);
                fichaJ3.setEnabled(false);
                txtNombreJ4.setEnabled(false);
                fichaJ4.setEnabled(false);
                break;
            }
            case "3" -> {
                txtNombreJ3.setEnabled(true);
                fichaJ3.setEnabled(true);
                break;
            }
            case "4" -> {
                txtNombreJ3.setEnabled(true);
                fichaJ3.setEnabled(true);
                txtNombreJ4.setEnabled(true);
                fichaJ4.setEnabled(true);
                break;
            }
            default -> {
                break;
            }
            
        }
       
    }//GEN-LAST:event_cantjugadoresActionPerformed

    private void fichaJ1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fichaJ1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fichaJ1ActionPerformed

    private void JugarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JugarActionPerformed
      
        switch (cantjugadores.getSelectedItem().toString()) {
            case "2": {
                if (fichaJ1.getSelectedItem().equals(fichaJ2.getSelectedItem())) {
                    JOptionPane.showMessageDialog(null, "Error, cada jugador debe escoger fichas de color diferentes.");
                    return;
                } else {
                    this.juego = new serpientesyEscaleras("2", this.tamañotablero.getSelectedItem().toString());
                    juego.registrarJugadores(this.txtNombreJ1.getText(), this.fichaJ1.getSelectedItem().toString());
                    juego.registrarJugadores(this.txtNombreJ2.getText(), this.fichaJ2.getSelectedItem().toString());
                }
                break;
            }
            case "3": {
                if (fichaJ1.getSelectedItem().equals(fichaJ2.getSelectedItem()) || fichaJ1.getSelectedItem().equals(fichaJ3.getSelectedItem()) || fichaJ2.getSelectedItem().equals(fichaJ3.getSelectedItem())) {
                    JOptionPane.showMessageDialog(null, "Error, cada jugador debe escoger fichas de color diferentes.");
                    return;
                } else {
                    this.juego = new serpientesyEscaleras("3", this.tamañotablero.getSelectedItem().toString());
                    juego.registrarJugadores(this.txtNombreJ1.getText(), this.fichaJ1.getSelectedItem().toString());
                    juego.registrarJugadores(this.txtNombreJ2.getText(), this.fichaJ2.getSelectedItem().toString());
                    juego.registrarJugadores(this.txtNombreJ3.getText(), this.fichaJ3.getSelectedItem().toString());
                }
                break;
            }
            case "4": {
                if (fichaJ1.getSelectedItem().equals(fichaJ2.getSelectedItem()) || fichaJ1.getSelectedItem().equals(fichaJ3.getSelectedItem()) || fichaJ1.getSelectedItem().equals(fichaJ4.getSelectedItem()) || fichaJ2.getSelectedItem().equals(fichaJ3.getSelectedItem()) || fichaJ3.getSelectedItem().equals(fichaJ4.getSelectedItem())) {
                    JOptionPane.showMessageDialog(null, "Error, cada jugador debe escoger fichas de color diferentes.");
                    return;
                } else {
                    this.juego = new serpientesyEscaleras(this.cantjugadores.getSelectedItem().toString(), this.tamañotablero.getSelectedItem().toString());
                    juego.registrarJugadores(this.txtNombreJ1.getText(), this.fichaJ1.getSelectedItem().toString());
                    juego.registrarJugadores(this.txtNombreJ2.getText(), this.fichaJ2.getSelectedItem().toString());
                    juego.registrarJugadores(this.txtNombreJ3.getText(), this.fichaJ3.getSelectedItem().toString());
                    juego.registrarJugadores(this.txtNombreJ4.getText(), this.fichaJ4.getSelectedItem().toString());
                }

            }
        }

        switch (tamañotablero.getSelectedItem().toString()){
            case "10":{
                Tablero10x10 tab10 = new Tablero10x10(juego);
                tab10.setVisible(true);
                break;
            }
            case "13":{
                Tablero13x13 tab13 = new Tablero13x13(juego);
                tab13.setVisible(true);
                break;
            }
            case "15":{
                Tablero15x15 tab15 = new Tablero15x15(juego);
                tab15.setVisible(true);
                break;
            }     
        }
    }//GEN-LAST:event_JugarActionPerformed

    /**
     * @param args the command line arguments
     */

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Jugar;
    private javax.swing.JComboBox<String> cantjugadores;
    private javax.swing.JComboBox<String> fichaJ1;
    private javax.swing.JComboBox<String> fichaJ2;
    private javax.swing.JComboBox<String> fichaJ3;
    private javax.swing.JComboBox<String> fichaJ4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private java.awt.Panel panel1;
    private javax.swing.JComboBox<String> tamañotablero;
    private javax.swing.JLabel titulo;
    private javax.swing.JTextField txtNombreJ1;
    private javax.swing.JTextField txtNombreJ2;
    private javax.swing.JTextField txtNombreJ3;
    private javax.swing.JTextField txtNombreJ4;
    // End of variables declaration//GEN-END:variables
}
